New Cisco and Validated Patterns team partnership blog
validatedpatterns/docs pull request #398
Opened 2024-01-16 22:49 UTC by claudiol

* Deploying Multicloud GitOps with Cisco FlashStack Data Center and Portworx Enterprise
** Reviewed-by: Paniraja Koppa pkoppa@cisco.com
** Reviewed-by: Andrew Beekhof abeekhof@redhat.com

- CISCO Blog for MCG FlashStack and Portworx
- Added header for blog
- Removed alias from header

2024-01-16 22:49 UTC, mbaldessari commented
<!-- add-pr-comment:add-pr-comment -->

This is an automated message:

You can preview this docs PR at http://398.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

2024-01-17 15:44 UTC, mbaldessari commented
/lgtm

2024-01-17 15:47 UTC, mhjacks requested changes
Minor nit on spacing. I'm not sure we should mention Quay - I looked at the whitepaper and didn't see a reference there either.

2024-01-17 15:47 UTC, mhjacks commented on content/blog/2024-01-16-deploying-mcg-with-cisco-flashstack-portworx.md
> +The deployment of [Red Hat OpenShift Container Platform](https://www.redhat.com/en/technologies/cloud-computing/openshift/container-platform) serves as a cornerstone of this solution. The Multicloud
MCGO doesn't deploy Quay, normally. Did Cisco include that?

```and[Portworx Enterprise]```
^ Need a space here

2024-01-17 16:32 UTC, mhjacks commented
Thanks for the update.

/lgtm

2024-01-17 16:35 UTC, mbaldessari commented
/approve

2024-01-17 16:46 UTC, merged